from agentscope.agents import DialogAgent
from src.database.db_manager import DBManager

class FeedbackAgent(DialogAgent):
    def __init__(self, name, sys_prompt, model_config_name):
        super().__init__(name=name, sys_prompt=sys_prompt, model_config_name=model_config_name)
        self.db = DBManager()
        
    def reply(self, x=None):
        sql_query = x.content
        
        # Basic cleanup of markdown sql blocks if generated by LLM
        if "```sql" in sql_query:
            sql_query = sql_query.split("```sql")[1].split("```")[0].strip()
        elif "```" in sql_query:
            sql_query = sql_query.split("```")[1].split("```")[0].strip()
            
        try:
            result = self.db.execute_query(sql_query)
            feedback = f"Execution successful. Result: {result}"
        except Exception as e:
            feedback = f"Execution failed. Error: {str(e)}"
            
        # The feedback agent responds with the execution result
        from agentscope.message import Msg
        response_msg = Msg(self.name, content=feedback, role="assistant")
        self.speak(response_msg)
        
        return response_msg
